import type { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";
import { routing } from "@/i18n/routing";

type Props = { params: Promise<{ locale: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params;
  return {
    title: "Privacy Policy | Overwatch",
    description: "Privacy Policy for Overwatch Security and Surveillance.",
    alternates: {
      canonical: `/${locale}/privacy`,
      languages: Object.fromEntries(routing.locales.map((loc) => [loc, `/${loc}/privacy`])),
    },
  };
}

export default async function PrivacyPage({ params }: Props) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <main className="py-32 px-4 sm:px-6 lg:px-8 bg-primary-dark min-h-screen text-muted selection:bg-accent/30">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-4">Privacy Policy</h1>
        <p className="mb-12">Last Updated: July 2026</p>

        <div className="space-y-8 text-lg leading-relaxed">
          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">1. Introduction</h2>
            <p>
              {'Overwatch Lda ("Overwatch", "we", "us", or "our") respects your privacy and is committed to protecting the personal data of our clients, website visitors, and individuals recorded by our security systems. This Privacy Policy explains how we collect, use, store, and safeguard your data when you use our website, interact with our services, or are monitored by our CCTV and AI systems on behalf of our clients.'}
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">2. The Information We Collect</h2>
            <p className="font-semibold text-foreground mt-4 mb-2">A. Information provided directly by you:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Contact Information:</strong> Name, email address, phone number, and company details when you request a security assessment or contact us.</li>
              <li><strong>Account Information:</strong> Credentials used to access the Overwatch client dashboard.</li>
            </ul>

            <p className="font-semibold text-foreground mt-6 mb-2">B. Information collected through our Security Services:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Video & Audio Feeds:</strong> Live and recorded CCTV footage from cameras installed at client premises.</li>
              <li><strong>AI Metadata:</strong> Analytical data generated by our AI systems, including object detection (vehicles, persons), intrusion alerts, and movement tracking.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">3. How We Use Your Data</h2>
            <p>We use the collected information for the following purposes:</p>
            <ul className="list-disc pl-6 mt-4 space-y-2">
              <li>To provide, manage, and monitor the security services contracted by our clients.</li>
              <li>To detect, verify, and respond to security threats, intrusions, and unauthorized access using our surveillance control room.</li>
              <li>To communicate with you regarding your account, technical support, and critical security alerts.</li>
              <li>To train and improve our AI detection algorithms (video data used for this purpose is aggregated and anonymized wherever possible).</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">4. Data Controller vs. Data Processor</h2>
            <p>
              For the video surveillance footage and AI metadata collected on our clients&apos; premises, the <strong>Client is the Data Controller</strong>. Overwatch acts strictly as the <strong>Data Processor</strong>, processing this footage solely on the instructions of the client to ensure the security of their site. Any individual wishing to exercise their privacy rights regarding CCTV footage should contact the respective property owner (the client) directly.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">5. Data Retention and Security</h2>
            <p>
              We implement industry-standard encryption, firewalls, and strict access controls within our surveillance control room to protect all data against unauthorized access, alteration, or destruction. 
            </p>
            <p className="mt-4">
              CCTV footage is retained only for the period specified in the client&apos;s contract (typically 14 to 30 days) unless required longer for an ongoing security investigation or law enforcement request, after which it is securely deleted.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">6. Sharing of Information</h2>
            <p>
              We do not sell your personal data. We may share data with:
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2">
              <li><strong>Law Enforcement:</strong> When legally required to do so, or when turning over evidence of a crime detected on a client&apos;s premises.</li>
              <li><strong>Service Providers:</strong> Trusted third-party infrastructure providers (e.g., cloud hosting) who are bound by strict confidentiality agreements.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">7. Contact Us</h2>
            <p>
              If you have any questions or concerns about this Privacy Policy or our data practices, please contact us at:
            </p>
            <p className="mt-4 font-mono text-accent">comercial@overwatchmoz.com</p>
          </section>
        </div>
      </div>
    </main>
  );
}
